/* Card Vault — incremental comp-refresh runner (window.CV2)
 * WHERE TO RUN: paste/inject this into an eBay.com tab where Drew is LOGGED IN
 *   (same-origin cookies are required for eBay sold/active fetches).
 * WHAT IT DOES: pulls the stalest cards from Supabase (oldest value_date first,
 *   highest value first), fetches eBay sold + active per card, writes the
 *   recent-sales + active-listings to each card profile (ingest-market-items),
 *   and updates the median value ONLY for standard cards under the protect
 *   threshold. Premium / graded-gem / Card-Ladder / sketch cards get their
 *   sales+listings refreshed but their VALUE is never auto-overwritten.
 * USAGE (in the eBay tab console or via injection):
 *   CV2.refreshStale({ staleDays:7, maxCards:150 })          // weekly top tier
 *   CV2.refreshStale({ staleDays:30, maxCards:600, maxValue:100 })  // monthly mid tier
 *   then poll window.CV2.prog  (has {i,total,updated,items,protectedCnt,nocomp,errs,done,log})
 * OPTIONS: staleDays(7) maxCards(150) autoUpdateMaxValue(100, protect >=) maxValue(null, ceiling filter)
 */
(()=>{
const SUPA='https://kcmrmswazprkizbzewpm.supabase.co';
const ANON='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjbXJtc3dhenBya2l6Ynpld3BtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg1NTEzMzAsImV4cCI6MjEwNDEyNzMzMH0.EuB77E8I0b6HzdK8zfDG1qlg-q_k0FUej6pYLyEFiJI';
const SECRET='cv_ingest_7Kq2mZ';
const GR=/\b(psa|bgs|sgc|cgc|gma|beckett|hga|ace|csg|tag|rcg)\b/i;
const money=t=>{const m=(t||'').replace(/,/g,'').match(/\$\s?([0-9]+(?:\.[0-9]{2})?)/);return m?parseFloat(m[1]):null;};
const med=a=>{if(!a.length)return null;const s=[...a].sort((x,y)=>x-y);const m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2;};
function lastname(p){if(!p)return '';let w=(p+'').toLowerCase().replace(/[^a-z0-9\s'-]/g,' ').trim().split(/\s+/);const stop=['jr','sr','ii','iii','psa','sgc','bgs','cgc','rc'];while(w.length>1&&stop.includes(w[w.length-1]))w.pop();return w[w.length-1]||'';}
function gradeInfo(card){const g=(card.grade||'').toString();const grr=(card.grader||'').toString();if(!g||/^raw$/i.test(g)||(/raw/i.test(g)&&!GR.test(g)&&!grr)){return {graded:false};}const num=(g.match(/\b(10|9\.5|9|8\.5|8|7\.5|7|6\.5|6|5\.5|5|4|3|2|1\.5|1)\b/)||[])[0];return {graded:true,num};}
function buildQuery(c){const parts=[];const yr=(c.year||'').toString().match(/(19|20)\d{2}/);if(yr)parts.push(yr[0]);if(c.player)parts.push((c.player+'').replace(/\b(psa|sgc|bgs|cgc)\b/gi,'').trim());if(c.set_name)parts.push(c.set_name);if(c.card_number)parts.push(c.card_number);const gi=gradeInfo(c);if(gi.graded&&gi.num){parts.push((c.grader||'')+' '+gi.num);}return parts.join(' ').replace(/\s+/g,' ').trim().slice(0,80);}
async function fetchList(q,sold){const url='https://www.ebay.com/sch/i.html?_nkw='+encodeURIComponent(q)+'&_sacat=0&_ipg=60&LH_Complete=1'+(sold?'&LH_Sold=1':'');const ctl=new AbortController();const to=setTimeout(()=>ctl.abort(),9000);let html;try{const r=await fetch(url,{credentials:'include',signal:ctl.signal});html=await r.text();}finally{clearTimeout(to);}const doc=new DOMParser().parseFromString(html,'text/html');const out=[];for(const n of [...doc.querySelectorAll('li.s-item, li.s-card, .su-card-container')]){const tEl=n.querySelector('.s-item__title, .s-card__title, .su-styled-text.primary.default, [role=heading]');const title=tEl?tEl.textContent.trim():'';if(!title||/Shop on eBay/i.test(title))continue;const pEl=n.querySelector('.s-item__price, .s-card__price');const price=money(pEl?pEl.textContent:'');if(price==null)continue;const dm=(n.textContent||'').match(/Sold\s+([A-Z][a-z]{2}\s+\d{1,2},\s+\d{4})/);const aEl=n.querySelector('a.s-item__link, a[href*="/itm/"]');const url2=aEl?aEl.href.split('?')[0]:null;const iEl=n.querySelector('img');const img=iEl?(iEl.src||iEl.getAttribute('data-src')):null;if(sold&&!dm)continue;out.push({title:title.slice(0,140),price,date:dm?dm[1]:null,url:url2,img});}return out;}
function isMatch(title,ln,gi){const s=title.toLowerCase();if(ln&&!s.includes(ln))return false;if(gi.graded){if(gi.num&&!s.includes(gi.num))return false;if(!GR.test(title))return false;}else{if(GR.test(title))return false;}return true;}
async function post(path,body){const r=await fetch(SUPA+'/functions/v1/'+path,{method:'POST',headers:{'content-type':'application/json','x-ingest-secret':SECRET,'apikey':ANON},body:JSON.stringify(body)});return r.ok;}
async function getStale(staleDays,maxCards,maxValue){const d=new Date(Date.now()-staleDays*86400000).toISOString().slice(0,10);const sel='id,ref,player,year,set_name,variation,card_number,serial,grade,grader,sport,current_value,value_source,value_date,status';let url=SUPA+'/rest/v1/cards?select='+sel+'&order=current_value.desc.nullslast&limit='+maxCards+'&or=(value_date.is.null,value_date.lt.'+d+')';if(maxValue!=null)url+='&current_value=lte.'+maxValue+'&current_value=gt.0';const r=await fetch(url,{headers:{apikey:ANON,Authorization:'Bearer '+ANON}});return await r.json();}
window.CV2={prog:{},async refreshStale(opts){opts=opts||{};const staleDays=opts.staleDays??7;const maxCards=opts.maxCards??150;const protMin=opts.autoUpdateMaxValue??100;const maxValue=opts.maxValue??null;const cards=(await getStale(staleDays,maxCards,maxValue)).filter(c=>c.status!=='sold');const P={total:cards.length,i:0,updated:0,items:0,protectedCnt:0,nocomp:0,errs:0,done:false,log:[]};window.CV2.prog=P;const today=new Date().toISOString().slice(0,10);for(const c of cards){try{const gi=gradeInfo(c);const ln=lastname(c.player);const q=buildQuery(c);const sold=await fetchList(q,true);await new Promise(r=>setTimeout(r,200));let active=[];try{active=await fetchList(q,false);}catch(e){}const items=[];const mSold=[];for(const s of sold.slice(0,60)){const m=isMatch(s.title,ln,gi);if(m)mSold.push(s.price);items.push({card_id:c.id,kind:'sold',title:s.title,price:s.price,item_date:s.date,url:s.url,image:s.img,matched:m,source:'ebay'});}for(const a of active.slice(0,40)){const m=isMatch(a.title,ln,gi);items.push({card_id:c.id,kind:'active',title:a.title,price:a.price,item_date:null,url:a.url,image:a.img,matched:m,source:'ebay'});}if(items.length){const ok=await post('ingest-market-items',{items});if(ok)P.items++;}const cv=parseFloat(c.current_value)||0;const vs=(c.value_source||'');const protectedCard=cv>=protMin||/cardladder|sketch/.test(vs)||(gi.graded&&(gi.num==='10'||gi.num==='9.5')&&cv>=60);const mm=med(mSold);let action='no-comp';if(mSold.length>=1&&mm!=null){if(protectedCard){action='protected(items only)';P.protectedCnt++;}else{const src=mSold.length>=3?'ebay-median':'ebay-thin';await post('lot-ops',{op:'set_card',card_id:c.id,current_value:Math.round(mm*100)/100,value_source:src,value_date:today});action='updated $'+(Math.round(mm*100)/100)+' ('+mSold.length+')';P.updated++;}}else{if(protectedCard)P.protectedCnt++;else P.nocomp++;}P.log.push(c.ref+': '+action);}catch(e){P.errs++;P.log.push((c.ref||'?')+': ERR '+String(e).slice(0,30));}P.i++;await new Promise(r=>setTimeout(r,250));}P.done=true;return P;}};
return 'CV2 installed';
})();
