/* Card Vault — incremental comp-refresh runner (window.CV2)  [v3 — accurate matching + grade buckets]
 * WHERE TO RUN: inject into an eBay.com tab where Drew is LOGGED IN (same-origin cookies needed).
 * WHAT IT DOES: pulls the stalest cards from Supabase (oldest value_date, highest value first),
 *   fetches eBay sold + active per card, and for each stores ONLY the right-player, non-reprint
 *   listings (drops other players and reprints). matched = SAME grade as the card (raw->raw,
 *   PSA5->PSA5; auto cards require an auto listing). Median of matched(=same-grade) sold is the
 *   value. Auto-updates value ONLY for standard cards under the protect threshold; premium /
 *   graded-gem / Card-Ladder / sketch cards get sales+listings refreshed, value untouched.
 * USAGE:  CV2.refreshStale({ staleDays:7, maxCards:150 })            // weekly top tier
 *         CV2.refreshStale({ staleDays:30, maxCards:600, maxValue:100 })  // monthly mid tier
 *   then poll window.CV2.prog until prog.done.
 */
(()=>{
const SUPA='https://kcmrmswazprkizbzewpm.supabase.co';
const ANON='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjbXJtc3dhenBya2l6Ynpld3BtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg1NTEzMzAsImV4cCI6MjEwNDEyNzMzMH0.EuB77E8I0b6HzdK8zfDG1qlg-q_k0FUej6pYLyEFiJI';
const SECRET='cv_ingest_7Kq2mZ';
const money=t=>{const m=(t||'').replace(/,/g,'').match(/\$\s?([0-9]+(?:\.[0-9]{2})?)/);return m?parseFloat(m[1]):null;};
const med=a=>{if(!a.length)return null;const s=[...a].sort((x,y)=>x-y);const m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2;};
function lastname(p){if(!p)return '';let w=(p+'').toLowerCase().replace(/[^a-z0-9\s'-]/g,' ').trim().split(/\s+/);const stop=['jr','sr','ii','iii','psa','sgc','bgs','cgc','rc','hof'];while(w.length>1&&stop.includes(w[w.length-1]))w.pop();return w[w.length-1]||'';}
function itemGrade(t){const m=String(t).match(/\b(PSA|BGS|BVG|SGC|CGC|CSG|BAS|HGA|GMA|TAG|RCG)\s*\.?\s*(10|[1-9](?:\.5)?)\b/i);if(m)return{g:true,gr:m[1].toUpperCase(),n:m[2]};if(/\b(psa|bgs|sgc|cgc|graded|gem\s*mint)\b/i.test(t))return{g:true,gr:'',n:''};return{g:false};}
function cardGI(c){const g=(c.grade||'').toString();if(!g||/^raw$/i.test(g.trim())){return{g:false};}const m=g.match(/\b(PSA|BGS|BVG|SGC|CGC|CSG|BAS|HGA)\s*\.?\s*(10|[1-9](?:\.5)?)/i);if(m)return{g:true,gr:m[1].toUpperCase(),n:m[2]};if(c.grader||/graded/i.test(g))return{g:true,gr:(c.grader||'').toUpperCase(),n:(g.match(/\b(10|[1-9](?:\.5)?)\b/)||[])[0]||''};return{g:false};}
function isReprint(t){return /\b(reprint|re-print|rp|custom|aceo|novelty|proxy|fantasy)\b/i.test(t);}
function autoCard(c){return !!c.is_auto||/auto|signed|autograph/i.test((c.grade||'')+' '+(c.variation||''));}
function autoItem(t){return /\b(auto|autographed|autograph|signed|on[\s-]?card)\b/i.test(t);}
function bucketOf(t,c){const ci=cardGI(c),ii=itemGrade(t);let b;if(ci.g){if(!ii.g)b='raw';else if(ii.n&&ci.n&&ii.n===ci.n&&(!ii.gr||!ci.gr||ii.gr===ci.gr))b='same';else b='different';}else{b=ii.g?'different':'same';}if(b==='same'&&autoCard(c)!==autoItem(t))b='different';return b;}
function buildQuery(c){const parts=[];const yr=(c.year||'').toString().match(/(19|20)\d{2}/);if(yr)parts.push(yr[0]);if(c.player)parts.push((c.player+'').replace(/\b(psa|sgc|bgs|cgc)\b/gi,'').trim());if(c.set_name)parts.push(c.set_name);if(c.card_number)parts.push(c.card_number);const gi=cardGI(c);if(gi.g&&gi.n){parts.push((c.grader||'')+' '+gi.n);}return parts.join(' ').replace(/\s+/g,' ').trim().slice(0,80);}
async function fetchList(q,sold){const url='https://www.ebay.com/sch/i.html?_nkw='+encodeURIComponent(q)+'&_sacat=0&_ipg=60&LH_Complete=1'+(sold?'&LH_Sold=1':'');const ctl=new AbortController();const to=setTimeout(()=>ctl.abort(),9000);let html;try{const r=await fetch(url,{credentials:'include',signal:ctl.signal});html=await r.text();}finally{clearTimeout(to);}const doc=new DOMParser().parseFromString(html,'text/html');const out=[];for(const n of [...doc.querySelectorAll('li.s-item, li.s-card, .su-card-container')]){const tEl=n.querySelector('.s-item__title, .s-card__title, .su-styled-text.primary.default, [role=heading]');const title=tEl?tEl.textContent.trim():'';if(!title||/Shop on eBay/i.test(title))continue;const pEl=n.querySelector('.s-item__price, .s-card__price');const price=money(pEl?pEl.textContent:'');if(price==null)continue;const dm=(n.textContent||'').match(/Sold\s+([A-Z][a-z]{2}\s+\d{1,2},\s+\d{4})/);const aEl=n.querySelector('a.s-item__link, a[href*="/itm/"]');const url2=aEl?aEl.href.split('?')[0]:null;const iEl=n.querySelector('img');const img=iEl?(iEl.src||iEl.getAttribute('data-src')):null;if(sold&&!dm)continue;out.push({title:title.slice(0,140),price,date:dm?dm[1]:null,url:url2,img});}return out;}
async function post(path,body){const r=await fetch(SUPA+'/functions/v1/'+path,{method:'POST',headers:{'content-type':'application/json','x-ingest-secret':SECRET,'apikey':ANON},body:JSON.stringify(body)});return r.ok;}
async function getStale(staleDays,maxCards,maxValue){const d=new Date(Date.now()-staleDays*86400000).toISOString().slice(0,10);const sel='id,ref,player,year,set_name,variation,card_number,serial,grade,grader,sport,is_auto,current_value,value_source,value_date,status';let url=SUPA+'/rest/v1/cards?select='+sel+'&order=current_value.desc.nullslast&limit='+maxCards+'&or=(value_date.is.null,value_date.lt.'+d+')';if(maxValue!=null)url+='&current_value=lte.'+maxValue+'&current_value=gt.0';const r=await fetch(url,{headers:{apikey:ANON,Authorization:'Bearer '+ANON}});return await r.json();}
async function refreshCard(c){const ln=lastname(c.player);const q=buildQuery(c);const sold=await fetchList(q,true);await new Promise(r=>setTimeout(r,200));let active=[];try{active=await fetchList(q,false);}catch(e){}
 function keep(x){const t=(x.title||'').toLowerCase();if(!t)return false;if(isReprint(t))return false;if(ln&&!t.includes(ln))return false;return true;}
 const items=[];const sameSold=[];
 for(const s of sold.slice(0,80)){if(!keep(s))continue;const bk=bucketOf(s.title,c);if(bk==='same')sameSold.push(s.price);items.push({card_id:c.id,kind:'sold',title:s.title,price:s.price,item_date:s.date,url:s.url,image:s.img,matched:bk==='same',source:'ebay'});if(items.length>=60)break;}
 for(const a of active.slice(0,60)){if(!keep(a))continue;const bk=bucketOf(a.title,c);items.push({card_id:c.id,kind:'active',title:a.title,price:a.price,item_date:null,url:a.url,image:a.img,matched:bk==='same',source:'ebay'});}
 return {items,mm:med(sameSold),nSame:sameSold.length};}
window.CV2={prog:{},async refreshOne(cardId){const r=await fetch(SUPA+'/rest/v1/cards?id=eq.'+cardId+'&select=id,ref,player,year,set_name,variation,card_number,serial,grade,grader,sport,is_auto,current_value,value_source',{headers:{apikey:ANON,Authorization:'Bearer '+ANON}});const c=(await r.json())[0];if(!c)return 'no card';const {items,mm,nSame}=await refreshCard(c);if(items.length)await post('ingest-market-items',{items});return {ref:c.ref,items:items.length,sameSold:nSame,median:mm};},
async refreshStale(opts){opts=opts||{};const staleDays=opts.staleDays??7;const maxCards=opts.maxCards??150;const protMin=opts.autoUpdateMaxValue??100;const maxValue=opts.maxValue??null;const cards=(await getStale(staleDays,maxCards,maxValue)).filter(c=>c.status!=='sold');const P={total:cards.length,i:0,updated:0,items:0,protectedCnt:0,nocomp:0,errs:0,done:false,log:[]};window.CV2.prog=P;const today=new Date().toISOString().slice(0,10);for(const c of cards){try{const {items,mm,nSame}=await refreshCard(c);if(items.length){const ok=await post('ingest-market-items',{items});if(ok)P.items++;}const cv=parseFloat(c.current_value)||0;const vs=(c.value_source||'');const gi=cardGI(c);const protectedCard=cv>=protMin||/cardladder|sketch/.test(vs)||(gi.g&&(gi.n==='10'||gi.n==='9.5')&&cv>=60);let action='no-comp';if(nSame>=1&&mm!=null){if(protectedCard){action='protected(items only)';P.protectedCnt++;}else{const src=nSame>=3?'ebay-median':'ebay-thin';await post('lot-ops',{op:'set_card',card_id:c.id,current_value:Math.round(mm*100)/100,value_source:src,value_date:today});action='updated $'+(Math.round(mm*100)/100)+' ('+nSame+' same)';P.updated++;}}else{if(protectedCard)P.protectedCnt++;else P.nocomp++;}P.log.push(c.ref+': '+action);}catch(e){P.errs++;P.log.push((c.ref||'?')+': ERR '+String(e).slice(0,30));}P.i++;await new Promise(r=>setTimeout(r,250));}P.done=true;return P;}};
return 'CV2 v3 installed';
})();
